### ISSUE TITLE
New Alliance || Cache created for old alliance

### ISSUE THREAD

**Issue by akheva** [fatcat4096/MSF2CSV#10]
Without moving the cached file, need a way to run for a new alliance.
Current logic:

1. Login with new alliance credentials
2. msf2csv pulls cached roster link of old alliance cached data
3. Generates reports based on cached data and not on logged in user's alliance.

**Comment by fatcat4096** [comment]
Fixed this a while ago. Place your cached_data.msf file along with corresponding strike_teams.py and raids_and_lanes files in a directory named after the alliance. For example, cached_data-SIGMA.msf would go into a folder named SIGMA along with the customized .py files. 

Once this is done, running **MSF2CSV.exe SIGMA** or **py msf2csv.py SIGMA** will automatically use these files and place output in the same directory. Running **MSF2CSV.exe** or **py msf2csv.py** alone will automatically use these files if the MSF.gg login belongs to a member of SIGMA (automatically assumes MSF.gg alliance name if no alliance name is specified).
