### ISSUE TITLE
Problem when english is not the main language of the account

### ISSUE THREAD

**Issue by Tylian83** [fatcat4096/MSF2CSV#7]
As a french user of the website, i have to force the bot to switch to english language before extracting the characters. Even if the alliance page targeted is in english (with the `/en` in the uri), once i click on a member, the characters names are in french.

For this, I had to add some instructions to click on the english language. I put it in `process_website.py`, line 33 (after the login instruction) : 
```python
	try:
		wait = WebDriverWait(driver, 10)
		
		# Click on language selection
		language = wait.until(EC.element_to_be_clickable((By.CLASS_NAME, 'language-selector')))
		language.click()
		
		# Select english language 
		english = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'div.language-selector a[title="English"]')))
		english.click()
	except TimeoutException:
		print("Timed out. Unable to switch to english.")
```

**Comment by fatcat4096** [comment]
THANK YOU! This is great information! I will roll this in.

**Comment by fatcat4096** [comment]
Okay, this is included now. I tried making it language agnostic, but in hindsight it probably is best just to force everything to English for now. Thanks for the Language selection solution!
