### ISSUE TITLE
Encoding error on output file

### ISSUE THREAD

**Issue by Tylian83** [fatcat4096/MSF2CSV#8]
When all the extractions are done, and we try to generate and save the file, i've got an error about some encode issues : 
```
Found extracted traits in /static/js/0.71802ea4a42a748d20fb.js
Writing pivot tables to: P:\MSF2.1\
Traceback (most recent call last):
  File "P:\MSF2.1\msf2csv.py", line 120, in <module>
    main() # Just run myself
  File "P:\MSF2.1\msf2csv.py", line 99, in main
    open(filename+"incursion.html", 'w').write(html_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0394' in position 488161: character maps to <undefined>
```

I've fixed it by replacing the previous `open().write()` by : 
```python
	with open(filename+"incursion.html", 'w', encoding='utf-8') as f:
		print(html_file, file=f)  
```

Maybe it comes from my alliance name that have a special character in name (`ENDGΔMERS`), or something else ?

Plus : in the file `parse_contents.py` (line 64-65), i had to add some characters replacement, as some `\u202f` characters was found : 
```python
		member['tcp'] = int(member_row.find('td', attrs={'data-label':'Collection Power'}).text.replace('\u202f','').replace(',',''))
		member['stp'] = int(member_row.find('td', attrs={'data-label':'Strongest Team Power'}).text.replace('\u202f','').replace(',',''))
		member['mvp'] = int(member_row.find('td', attrs={'data-label':'War MVP'}).text.replace(',',''))
		member['tcc'] = int(member_row.find('td', attrs={'data-label':'Total Characters Collected'}).text.replace(',',''))
```

If you want some html files to test it, i can provite it 😃

**Comment by fatcat4096** [comment]
Thank you. Good feedback. \u202f is a Narrow No-Break Space (NNBSP). It's probably due to the localization, you guys don't use commas to indicate millions, thousands, etc.  Apologies that the code is definitely US/English focused at the moment.  

Ideally, we change it to just ignore anything but digits in the string. I'm thinking
int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'Collection Power'}).text))  
int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'Strongest Team Power'}).text))  
int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'War MVP'}).text))  
int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'Total Characters Collected'}).text))

**Comment by fatcat4096** [comment]
And thank you for the comments re: the special characters in the Alliance name! This is great. 
We already had to add in code to HTML codes/colors from Names and Alliance names. 
If this solves the problem re special characters / Unicode characters, I'll definitely use it! Thank you!

**Comment by Tylian83** [comment]
> Thank you. Good feedback. \u202f is a Narrow No-Break Space (NNBSP). It's probably due to the localization, you guys don't use commas to indicate millions, thousands, etc. Apologies that the code is definitely US/English focused at the moment.
> 
> Ideally, we change it to just ignore anything but digits in the string. I'm thinking int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'Collection Power'}).text)) int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'Strongest Team Power'}).text)) int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'War MVP'}).text)) int(re.sub(r"\D", "", member_row.find('td', attrs={'data-label':'Total Characters Collected'}).text))

Yeah, only some speace to separate millions and thousand here ^^.
And no problem. Your code help me so much to view the roster of all the alliance and all in one view. I was using the csv export option before and working with excel/sheets...but, as you know, the option magically disappeared. So many thanks to you if all I have to do is to add some tweak for my localization 😄

---
> And thank you for the comments re: the special characters in the Alliance name! This is great. We already had to add in code to HTML codes/colors from Names and Alliance names. If this solves the problem re special characters / Unicode characters, I'll definitely use it! Thank you!

Encoding problem is so annoying, so if it can help, you're welcome 😄

**Comment by fatcat4096** [comment]
Hey, regarding the Greek Delta character, I just changed the write operation to: 

	open(filename+"incursion.html", 'w', encoding='utf-8').write(html_file)    

And this seems to handle that character just fine. Can you verify? Also, please drop me a message on Discord at fatcat4096 -- I had a question about a Issue message I got from you about extract_traits.

**Comment by Tylian83** [comment]
It works well with this write operation. Thanks :)

**Comment by fatcat4096** [comment]
Thank you, confirmed closed. 

At some point, I really should look at how to preserve the original Alliance names and user names instead of allowing them to be munged during processing. Someday. Someday.
